name: edgard_in_kimeria
description: Edgard in Kimeria.
publish_to: 'none'

version: 0.0.1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  bonfire: ^3.9.5
  flame_audio: ^2.0.5
  flame_splash_screen: ^0.1.0
  url_launcher: ^6.1.14

  darkness_dungeon: any
  flame: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/enemy/
    - assets/images/enemy/goblin/
    - assets/images/enemy/boss/
    - assets/images/player/
    - assets/images/items/
    - assets/images/tiled/
    - assets/audio/
    - resources/lang/en.json
    - resources/lang/ru.json

  fonts:
   - family: Normal
     fonts:
       - asset: fonts/font_pixel.ttf
